export default {
    FETCH_USER: 'FETCH_USER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SIGNUP: 'SIGNUP',
    SET_NOTIFICATION: 'SET_NOTIFICATION', 
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
}