export default {
    FETCH_USER: 'FETCH_USER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SIGNUP: 'SIGNUP',
    SET_NOTIFICATION: 'SET_NOTIFICATION', 
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
    TICKET_SEND: 'TICKET_SEND',
    TICKET_CLOSE: 'TICKET_CLOSE',

    VALIDATE_COMPANY: 'VALIDATE_COMPANY',
    INQUIRY_SUBMIT: 'INQUIRY_SUBMIT'
}